// Vortakeen Text exported by vkmake
// "|--THIS IS THE MAX LENGTH--|"
const unsigned short ENDTEXT_length = 44;
const unsigned char *ENDTEXT_text[] = {
"\x7e \x1f ",
"\x7e      TO BE CONTINUED...\x1f ",
"\x7e ",
"",
"",
"You must find your way onto",
"the Vorticon Mothership and",
"destroy all the horrible ",
"Tantalus Rays! If you don\'t",
"--THE EARTH EXPLODES!",
"Don\'t miss episode two!",
"",
"",
"And then on to Vorticon VI",
"where the whole planet ",
"awaits your arrival! Make",
"your way through all the ",
"Vorticon Cities and military"
"installations, and prepare ",
"yourself for the final ",
"confrontation with the ",
"Grand Intellect!  ",
"You won\'t believe the ",
"shocking finale!",
"",
"",
"The final episodes are ",
"available on github!",
"Play the whole trilogy,",
"or play some fan made mods!",
"",
"",
"VortaKeen was made by ",
"John314. For bug reports,",
"please read the README file.",
"",
"",
"",
" \x97 \x98  Commander Keen says:\x1f",
" \x99 \x9a     \"Hope you enjoyed\x1f",
"        the game. I did!\"",
"",
"",
"\x7e     THE END (for now...)",

};
