// Vortakeen Text exported by vkmake
// "|--THIS IS THE MAX LENGTH--|"
const unsigned short ENDTEXT_length = 40;
const unsigned char *ENDTEXT_text[] = {
"\x7e\x1f",
"\x7e          TO BE CONTINUED...\x1f",
"\x7e",
"",
"",
"You must find your way onto the Vorticon Mothership and destroy all the",
"horrible Tantalus Rays! If you don\'t--THE EARTH EXPLODES!  Don\'t miss",
"episode two!",
"",
"",
"And then on to Vorticon VI where the whole planet awaits your arrival! Make",
"your way through all the Vorticon Cities and military installations, and",
"prepare yourself for the final confrontation with the Grand Intellect!  You",
"won\'t believe the shocking finale!",
"",
"",
"The final episodes are available from Apogee Software Productions.  They are",
"only $15 each or $30 for the whole trilogy!",
"",
"",
"Send your check or money order to:",
"",
"",
"Apogee Software Productions\x1f",
"P.O. Box 476389\x1f",
"Garland, TX   75047",
"",
"",
"Or call: 1-800-852-5659.",
"",
"",
"(U.S. Funds only, and please include $2 for Shipping and Handling.)",
"",
"",
"",
" \x97\x98    Commander Keen says:\x1f",
" \x99\x9a        \"Hope you enjoyed\x1f",
"            the game. I did!\"",
"",
"",
"\x7e      THE END (for now...)",

};
