// Vortakeen Text exported by vkmake
// THIS FILE HAS BEEN FORMATED TO FIT THE GBA SCREEN

//"|--THIS IS THE MAX LENGTH--|"

const unsigned short HELPTEXT_length = 86;
const unsigned char *HELPTEXT_text[] = {
"    \x9f  \x9f \x9f\x9f\x9f\x9f \x9f    \x9f\x9f\x9f\x1f",
"    \x9f  \x9f \x9f    \x9f    \x9f  \x9f\x1f",
"    \x9f\x9f\x9f\x9f \x9f\x9f\x9f  \x9f    \x9f\x9f\x9f\x1f",
"    \x9f  \x9f \x9f    \x9f    \x9f\x1f",
"    \x9f  \x9f \x9f\x9f\x9f\x9f \x9f\x9f\x9f\x9f \x9f",
"",
"",
"You can move Commander Keen",
"with the D-Pad.",
"",
"",
"Let\'s look at the buttons",
"you need to know to play.",
"",
"BUTTON    WHAT IT DOES",
"",
"D-Pad     Move Keen around",
"",
"A         Jump",
"",
"L Shoulder Toggle Pogo",
"          (if you have one)",
"",
"B         Fire raygun\x1f",
"         (if it has charges)",
"",
"",
"OTHER IMPORTANT KEYS",
"",
"SELECT  Status screen",
"",
"F1            Help!",
"",
"F2            Sound on/off",
"",
"F3            Music on/off",
"",
"F5            Save Game",
"",
"START         Quit",
"",
"",
"When you are on the Mars ",
"map, you may be blocked by a",
"city, shrine, or other",
"obstacle.  You must enter ",
"the city (press A) and ",
"finish it before proceeding.",
"",
"When you enter a city, you ",
"can get things by simply ",
"running into them.",
"",
"If you cannot pass through a",
"door, there may be a ",
"\"keycard\" that the door",
"requires.  This keycard will",
"be the same color as the ",
"door.",
"",
"\x7e       TREASURES",
"",
"Lollipop   \x84\x85    100 points\x1f",
"           \x86\x87",
"",
"Soda       \x88\x89    200 points\x1f",
"           \x8a\x8b",
"",
"Pi\x7a\x7aa      \x80\x81    500 points\x1f",
"           \x82\x83",
"",
"Book       \x8c\x8d    1000 points\x1f",
"           \x8e\x90",
"",
"Teddy Bear \x91\x92    5000 points\x1f",
"           \x94\x95",
"",
"You get an extra Keen",
"every 20,000 points.",
"",
"",
" \x97\x98 Commander Keen says:\x1f",
" \x99\x9a     \"Get to Episode Two\x1f",
"         before the Earth\x1f",
"         explodes!\"",
"",
"\x7e      END OF HELP",

};
