// Vortakeen Text exported by vkmake
// THIS FILE HAS BEEN FORMATED TO FIT THE GBA SCREEN
//"|--THIS IS THE MAX LENGTH--|"
const unsigned short STORYTXT_length = 164;
const unsigned char *STORYTXT_text[] = {
"\x7e       COMMANDER KEEN\x1f ",
"\x7e            in\x1f ",
"\x7e  \"Invasion of the Vorticons\"",
"",
"\x7e The following text has been",
"\x7e formated to fit this screen",
"",
"Billy Blaze, eight year-old",
"genius, working diligently ",
"in his backyard clubhouse ",
"has created an interstellar",
"starship from old soup cans,",
"rubber cement and plastic ",
"tubing.  While his folks are",
"out on the town and the",
"babysitter has fallen ",
"asleep, Billy travels into",
"his backyard workshop, dons",
" his brother\'s football ",
"helmet, and transforms ",
"into...",
"",
"      --COMMANDER KEEN--",
"      defender of Earth!",
"",
"In his ship, the",
"Bean-with-Bacon Megarocket,",
"Keen dispenses galactic ",
"justice with an iron hand!",
"",
"",
"\x7e  Episode 1: Marooned on Mars",
"",
"",
"In this episode, aliens from",
"the planet Vorticon VI find",
"out about the eight year-old",
"genius and plan his ",
"destruction.  While Keen is ",
"out exploring the mountains ",
"of Mars, the Vorticons steal",
"vital parts of his ship and",
"take them to distant Martian",
"cities!  Can Keen recover ",
"all the pieces of his ship ",
"and repel the Vorticon ",
"invasion?  Will he make it ",
"back before his parents get ",
"home?  Stay tuned!",
"",
"\x7e  WHAT THE VORTICONS STOLE ",
"",
"The Bean-with-Bacon ",
"Megarocket was constructed ",
"from objects around the ",
"house that you have ",
"\"modified\" into starship",
"parts:",
"",
"\x09  JOYSTICK Manual control.",
"",
"\x09  CAR BATTERY Systems power.",
"",
"\x09  VACUUM Ion propulsion unit",
"",
"\x09  EVERCLEAR  Fuel.",
"",
"",
"",
"The Vorticons have taken ",
"these pieces to the far ",
"reaches of Mars and are",
"guarding them.  You must",
"find the members of this ",
"Vorticon outpost and wrest",
"the parts back from their ",
"wicked, clawed hands!",
"",
"\x7e     INFORMATION ON MARS",
"",
"Unbeknownst to NASA, when ",
"the Viking Lander settled ",
"to the surface of Mars, it",
"caused a major political ",
"upheaval.  Viking actually ",
"landed on the despotic ",
"Martian king!  The Yorps ",
"(the extremely friendly ",
"one-eyed Martians) were ",
"free from enslavement, and",
"the Gargs (the vicious, ",
"aggressive Martians) were",
"angry.",
"",
"The Martians created robots",
"for menial work and guard ",
"duties.  Beware of the",
"tank-like Guard Robots",
"--they are VERY good at",
"   what they do.",
"",
"Martians have been visiting",
"Earth in UFOs for decades.",
"  Why?  They come to Earth ",
"for one reason",
"--THEY WANT OUR TOYS.",
"Hula hoops and skateboards",
"are holy objects to them! ",
"Who knows...you may find ",
"some toys useful!",
"",
"There are signs everywhere.",
"You haven\'t been able to",
"decipher them yet....",
"",
"\x7e    THE ADVENTURE BEGINS...",
"",
"Your task is before you.",
"Go get \'em, Commander Keen!",
"",
"____________________________",
"\x7e ",
"",
"And don\'t miss episodes Two",
"and Three in the ",
"\"Invasion of the Vorticons\"",
"trilogy!",
"",
"",
"\x7e  Episode 2: Earth Explodes",
"",
"Keen has assembled his ship",
"and returned home, only to",
"find the Vorticon Mothership",
"hovering over the Earth, ",
"ready to destroy all of ",
"Earth\'s cities and wonders!",
" Keen must sneak aboard, ",
"stop the imminent ",
"destruction of Earth and",
"find a way to neutralize",
"the Mothership!",
"  If he fails...THE EARTH",
"EXPLODES! (No pressure.)",
"",
"\x7e  Episode 3: Keen Must Die!",
"",
"Keen flies to the planet ",
"Vorticon VI to once and for",
"all rid the galaxy of the ",
"Vorticon menace.  ",
"The entire planet is ",
"waiting for his arrival, ",
"with only one order given",
"--Commander Keen must die!",
" What evil being is behind",
"all this?  Stay tuned for ",
"the climactic, shocking ",
"finale!",
"",
"",
" \x97 \x98  Commander Keen says:\x1f ",
" \x99 \x9a   \"You won\'t believe \x1f ",
"      what happens",
"      in Episode Three!\"",

};
